FROM python:3.12-slim
WORKDIR /app

# Como el contexto de build es la raíz del proyecto, Docker busca los archivos desde ahí.
COPY requirements.txt . 
COPY producer/producer.py . 

RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "-u", "producer.py"]