FROM python:3.12-slim
WORKDIR /app

# El contexto de build es la raíz del proyecto.
COPY requirements.txt . 
COPY consumer/consumer.py . 

RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "-u", "consumer.py"]