FROM python:3.12-slim
WORKDIR /app

# 1. Copia el requirements.txt que está en la raíz del proyecto
COPY requirements.txt .

# 2. Copia el script main.py que está dentro de la carpeta api_service/
COPY api_service/main.py .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto donde correrá la API
EXPOSE 8000

# Comando para iniciar el servidor uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]